# Generated by Django 4.1.3 on 2022-12-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
