# Generated by Django 4.1.3 on 2022-12-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_clients_client_rename_projects_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
